### ISSUE TITLE
When to provide English documents

### ISSUE THREAD

**Issue by shamerKill** [oracleNetworkProtocol/onpchain#11]
place see title, thanks.

**Comment by worryFree56** [comment]
go out

**Comment by TrimMine** [comment]
are you ok?

**Comment by TrimMine** [comment]
answer question with everybody .please

**Comment by shamerKill** [comment]
we need look at [the repertory](https://github.com/shamerKill/ONPChain-Browser) for I18n

**Comment by worryFree56** [comment]
close
